---
- name: Genereate client private key
  community.crypto.openssl_privatekey:
    path: "/etc/pki/CA/private/{{ client_hostname }}.key.pem"
    mode: '0400'

- name: Generate client Certificate Signing Request (CSR)
  community.crypto.openssl_csr_pipe:
    privatekey_path: "/etc/pki/CA/private/{{ client_hostname }}.key.pem"
    common_name: "{{ client_hostname }}"
    country_name: "{{ clientcert_country }}"
    email_address: "{{ clientcert_email }}"
    state_or_province_name: "{{ clientcert_state }}"
    organization_name: "{{ clientcert_org }}"
    key_usage:
      - nonRepudiation
      - digitalSignature
      - keyEncipherment
      - keyAgreement
    key_usage_critical: yes
    extended_key_usage:
      - serverAuth
    extended_key_usage_critical: yes
    digest: sha256
    subject_alt_name:
      - "DNS:{{ client_hostname }}"
  register: client_csr

- name: Generate client certificate
  community.crypto.x509_certificate:
    path: "/etc/pki/CA/certs/{{ client_hostname }}.cert.pem"
    csr_content: "{{ client_csr.csr }}"
    provider: ownca
    ownca_path: /etc/pki/CA/certs/ca.cert.pem
    ownca_privatekey_path: /etc/pki/CA/private/ca.key.pem
    ownca_privatekey_passphrase: "{{ rootca_password }}"
    ownca_not_after: +3650d
    mode: '0444'
