---
- name: Run preparation actions
  hosts: all
  tasks:

    - name: Install python3-cryptography package
      ansible.builtin.dnf:
        name: python3-cryptography
        state: present

- name: Install python for ubuntu
  hosts: ubuntu
  tasks:

    - name: Install python
      ansible.builtin.apt:
        name: python3
        state: present
...
