galaxy_info:
  author: Jacob Hunt
  description: Create signed client certificates

  license: GPL-3.0-only

  min_ansible_version: 2.9

  platforms:
  - name: Fedora
    versions:
    - 34
    - 33
    - 32
    - 31
  - name: Ubuntu
    versions:
    - focal
    - bionic
    - xenial
  - name: EL
    versions:
    - 8
    - 7

  galaxy_tags:
  - openssl
  - clientcertficate
  - rootca

dependencies: []